spring:
    profiles:
        active: local

    application:
        name: zuul-service

server:
    port: 4000

zuul:
    ribbonIsolationStrategy: THREAD
    threadPool:
        useSeparateThreadPools: true
    ignored-service: '*'
    prefix: /api
    routes:
        story-service: 
            path: /story/**
            serviceId: story-service
            stripPrefix: false
        notice-service: 
            path: /notice/**
            serviceId: notice-service
            stripPrefix: false
        board-service-sidecar: 
            path: /bbs/**
            serviceId: board-service-sidecar
            stripPrefix: false   
hystrix:
    command:
        story-service:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 20000
        notice-service:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 20000
        board-service-sidecar:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 20000
    
story-service:
    ribbon: 
        eureka:
            enabled: true
        NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
        ConnectTimeout: 5000
        ReadTimeout: 5000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100
    
notice-service:
    ribbon: 
        eureka:
            enabled: true
        NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
        ConnectTimeout: 5000
        ReadTimeout: 5000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100

board-service-sidecar:
    ribbon: 
        eureka:
            enabled: true
        NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
        ConnectTimeout: 5000
        ReadTimeout: 5000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100


eureka:
    client:
        healthcheck: true 
        fetch-registry: true
        serviceUrl:
            defaultZone: http://13.125.249.86:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        preferIpAddress: true
        
---

spring:
    profiles: docker

    cloud:
        inetutils:
            prfered-networks:
                - 10.0

    application:
        name: zuul-service

server:
    port: 4000

zuul:
    ribbonIsolationStrategy: THREAD
    threadPool:
        useSeparateThreadPools: true
    ignored-service: '*'
    prefix: /api
    routes:
        story-service: 
            path: /story/**
            serviceId: story-service
            stripPrefix: false
        notice-service: 
            path: /notice/**
            serviceId: notice-service
            stripPrefix: false
        board-service-sidecar: 
            path: /bbs/**
            serviceId: board-service-sidecar
            stripPrefix: false

hystrix:
    command:
        story-service:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 20000
        notice-service:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 20000
        board-service-sidecar:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 20000
    
story-service:
    ribbon: 
        eureka:
            enabled: true
        NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
        ConnectTimeout: 5000
        ReadTimeout: 5000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100
    
notice-service:
    ribbon: 
        eureka:
            enabled: true
        NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
        ConnectTimeout: 5000
        ReadTimeout: 5000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100

board-service-sidecar:
    ribbon: 
        eureka:
            enabled: true
        NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
        ConnectTimeout: 5000
        ReadTimeout: 5000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100

   
 
eureka:
    client:
        healthcheck: true 
        fetch-registry: true
        serviceUrl:
            defaultZone: http://13.125.249.86:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        preferIpAddress: true

