spring:
    profiles:
        active: local

    application:
        name: board-service-sidecar

server:
    port: 8766

sidecar:
    port: 3000
    health-uri: http://board-service:3000/bbs/health
    
 
eureka:
    client:
        healthcheck: true 
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: ${vcap.services.eureka-service.credentials.uri:http://13.125.249.86:8761}/eureka/

    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        preferIpAddress: true

---

spring:
    profiles: docker 

    cloud:
        inetutils:
            prefered-networks:
                - 10.0
    application:
        name: board-service-sidecar

server:
    port: 8766

sidecar:
    port: 3000
    health-uri: http://board-service:3000/bbs/health
    
 
eureka:
    client:
        healthcheck: true 
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: ${vcap.services.eureka-service.credentials.uri:http://13.125.249.86:8761}/eureka/

    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        preferIpAddress: true


